// Build time: the About and not-found pages, ported from the React app's App.tsx.
import type { VNode } from "preact";
import { defaultMap } from "../paths";
import type { Localized } from "../types";
import { LanguagePicker, LocalizedText } from "./common";

const aboutSections: Array<{ title: Localized; body: Localized }> = [
  { title: { en: "The goal", he: "המטרה" }, body: { en: "Help you enter an unfamiliar synagogue as an oriented participant: able to recognize the service, find its major movements, notice where you are, and anticipate what normally comes next.", he: "לעזור לכם להיכנס לבית כנסת שאינכם מכירים כמשתתפים בעלי התמצאות: לזהות את התפילה, למצוא את חלקיה העיקריים, להבין היכן אתם נמצאים ולצפות מה בדרך כלל בא אחר כך." } },
  { title: { en: "A visual roadmap", he: "מפת דרכים חזותית" }, body: { en: "The colored blocks are a service’s few large movements, in order, before any details. The high points are drawn largest: the Shema and its blessings, and the Shmoneh Esrei (“Amidah”), the central standing prayer. Mincha and Musaf have no Shema, so there the Shmoneh Esrei stands alone. Kaddish and Barkhu are the slim boxed joints between movements. Open a movement to see the prayers nested inside it, and open a prayer to read it. Beginnings, endings, and transitions are landmarks that help you recover your place.", he: "הגושים הצבעוניים מציגים את החלקים הגדולים של התפילה, לפי הסדר, לפני הפרטים. השיאים מצוירים הגדולים מכולם: קריאת שמע וברכותיה, ושמונה עשרה (\"עמידה\"), התפילה המרכזית בעמידה. במנחה ובמוסף אין קריאת שמע, ולכן שם שמונה עשרה עומדת לבדה. קדיש וברכו הם המפרקים הצרים והממוסגרים שבין החלקים. פתחו חלק כדי לראות את התפילות שבתוכו, ופתחו תפילה כדי לקרוא אותה. התחלות, סיומים ומעברים הם ציוני דרך שעוזרים למצוא מחדש את המקום." } },
  { title: { en: "Differences are expected", he: "השוני צפוי" }, body: { en: "Synagogues vary by nusach, community, calendar date, minyan, language, and local custom. The maps teach transferable landmarks, not one supposedly universal service. If the room differs, use the nearest familiar landmark, follow or listen, and ask which part of the service is happening.", he: "בתי כנסת שונים זה מזה לפי נוסח, קהילה, תאריך בלוח, מניין, שפה ומנהג מקומי. המפות מלמדות ציוני דרך שאפשר להעביר ממקום למקום, ולא תפילה אחת שמתיימרת להיות כלל־עולמית. אם הסדר במקום שונה, חפשו את ציון הדרך המוכר הקרוב, עקבו או הקשיבו, ושאלו באיזה חלק של התפילה נמצאים." } },
  { title: { en: "What this is not", he: "מה המיזם אינו" }, body: { en: "This is not a complete siddur, a test of Jewishness, a substitute for local guidance, or a promise that every synagogue works the same way. You do not need Hebrew fluency or perfect choreography to become more oriented.", he: "זה אינו סידור מלא, מבחן ליהדות, תחליף להדרכה מקומית או הבטחה שכל בתי הכנסת פועלים באותה דרך. אין צורך בשליטה בעברית או בתנועות מושלמות כדי להתמצא טוב יותר." } },
];

/** The back link goes to the map the reader came from; the browser script fills that in. */
export function About(): VNode {
  return <main className="about"><nav><a href={defaultMap} data-back-to-map="">{LocalizedText({ en: "← Service map", he: "מפת התפילה ←" })}</a>{LanguagePicker()}</nav><article className="copy"><h1 id="about-heading" tabIndex={-1}>{LocalizedText({ en: "About Jewish Literacy", he: "על מיזם האוריינות היהודית" })}</h1><p className="lead">{LocalizedText({ en: "Jewish Literacy is for people who grew up Jewish but learned little, or whose prayer experience looked nothing like a traditional synagogue service.", he: "מיזם האוריינות היהודית מיועד למי שגדלו כיהודים אך למדו מעט, או שחוויית התפילה שלהם לא דמתה כלל לתפילה מסורתית בבית הכנסת." })}</p>{aboutSections.map(section => <section className="about-section" key={section.title.en}><h2>{LocalizedText(section.title)}</h2><p>{LocalizedText(section.body)}</p></section>)}</article><footer>{LocalizedText({ en: "Learn the structure. Notice the transitions. Stay oriented when the details differ.", he: "למדו את המבנה. שימו לב למעברים. שמרו על התמצאות גם כשהפרטים שונים." })}</footer></main>;
}

export function NotFound(): VNode {
  return <main className="not-found"><h1 tabIndex={-1}>{LocalizedText({ en: "Page not found", he: "הדף לא נמצא" })}</h1><p>{LocalizedText({ en: "That Jewish Literacy view does not exist.", he: "העמוד המבוקש אינו קיים במיזם האוריינות היהודית." })}</p><a href={defaultMap}>{LocalizedText({ en: "Go to Weekday Shacharit", he: "מעבר לשחרית של חול" })}</a></main>;
}
